apiVersion: v1
kind: Service
metadata:
  name: victim-app
  namespace: victim
  labels:
    app: victim-app
  annotations:
    # UpCloud LoadBalancer will assign a private SDN IP
    service.beta.kubernetes.io/upcloud-load-balancer-mode: "tcp"
spec:
  type: LoadBalancer
  selector:
    app: victim-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
