#!/usr/bin/env bash
# bootstrap.sh — Creates UpCloud Object Storage for Terraform state, then initializes the main config.
# Usage: UPCLOUD_TOKEN=xxx ./scripts/bootstrap.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
BOOTSTRAP_DIR="$ROOT_DIR/terraform/bootstrap"
TERRAFORM_DIR="$ROOT_DIR/terraform"

OBJECT_STORAGE_REGION="${OBJECT_STORAGE_REGION:-europe-1}"

: "${UPCLOUD_TOKEN:?UPCLOUD_TOKEN must be set}"

echo "==> Bootstrapping Terraform state backend on UpCloud Object Storage"

# Apply bootstrap Terraform config to create Object Storage
cd "$BOOTSTRAP_DIR"

if [ ! -f ".terraform/terraform.tfstate" ]; then
  terraform init
fi

terraform apply -auto-approve \
  -var "upcloud_token=$UPCLOUD_TOKEN" \
  -var "object_storage_region=$OBJECT_STORAGE_REGION"

# Extract outputs
ENDPOINT=$(terraform output -raw object_storage_endpoint)
ACCESS_KEY=$(terraform output -raw access_key)
SECRET_KEY=$(terraform output -raw secret_key)

echo "==> Object Storage created"
echo "    Endpoint : $ENDPOINT"
echo "    Access Key: $ACCESS_KEY"

# Generate backend.tf for the main Terraform config
cat > "$TERRAFORM_DIR/backend.tf" <<EOF
# Auto-generated by scripts/bootstrap.sh — do not edit manually
terraform {
  backend "s3" {
    bucket                      = "terraform-state"
    key                         = "terraform.tfstate"
    region                      = "us-east-1"
    endpoint                    = "${ENDPOINT}"
    access_key                  = "${ACCESS_KEY}"
    secret_key                  = "${SECRET_KEY}"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    force_path_style            = true
  }
}
EOF

echo "==> Generated $TERRAFORM_DIR/backend.tf"

# Initialize main Terraform config
cd "$TERRAFORM_DIR"
terraform init -upgrade -reconfigure

echo ""
echo "==> Bootstrap complete. Run the following to deploy infrastructure:"
echo "    cd terraform && terraform apply -var upcloud_token=\$UPCLOUD_TOKEN"
